import java.awt.*;
import javax.swing.*;

public class CreateNewGameGUI {
    String strength = "Strength";
    String stamina = "Stamina        : ";
    String dexterity = "Dexterity     : ";
    String quickness = "Quickmess      : ";
    String intelligence = "Intelligence   : ";
    String spirit = "Spirit         : ";
    String life = "Life       :";
    String power = "Power    : ";

    String strVal = ": 0";
    String staVal = ": 0";
    String dexVal = ": 0";
    String quiVal = ": 0";
    String iqVal = ": 0";
    String sprVal = ": 0";

    String strBon = "+ 0";
    String staBon = "+ 0";
    String dexBon = "+ 0";
    String quiBon = "+ 0";
    String iqBon = "+ 0";
    String sprBon = "+ 0";

    JPanel newGame = new JPanel();
    JButton backToMain = new JButton("Back to Main");
    JPanel selectRace = new JPanel();
    JPanel selectStyle = new JPanel();
    JPanel selectClass = new JPanel();
    JPanel bonusSection = new JPanel();
    JPanel skillsSection = new JPanel();
    JButton start = new JButton("Start Game");
    JButton human = new JButton("Human");
    JButton dwarf = new JButton("Dwarven");
    JButton elven = new JButton("Elven");
    JButton kobold = new JButton("Kobold");
    JButton undead = new JButton("Undead");
    JButton troll = new JButton("Troll");
    JButton ogre = new JButton("Ogre");
    JButton draconic = new JButton("Draconis");
    JButton insane = new JButton("Insane");
    JButton divine = new JButton("Divine");
    JButton elusive = new JButton("Elusive");
    JButton diabolic = new JButton("Diabolical");
    JButton wise = new JButton("Wise");
    JButton warrior = new JButton("Warrior");
    JButton rogue = new JButton("Rogue");
    JButton mage = new JButton("Mage");
    JButton priest = new JButton("Priest");
    JButton necro = new JButton("Necro");
    JButton melee = new JButton("melee");
    JButton magic = new JButton("magic");
    JButton spark = new JButton("spark");
    JButton smite = new JButton("smite");
    JButton sweep = new JButton("sweep");
    JButton lifetap = new JButton("lifetap");
    JButton strP = new JButton("    +    ");
    JButton strN = new JButton("    -    ");
    JButton staP = new JButton("    +    ");
    JButton staN = new JButton("    -    ");
    JButton dexP = new JButton("    +    ");
    JButton dexN = new JButton("    -    ");
    JButton quiP = new JButton("    +    ");
    JButton quiN = new JButton("    -    ");
    JButton iqP = new JButton("    +    ");
    JButton iqN = new JButton("    -    ");
    JButton sprP = new JButton("    +    ");
    JButton sprN = new JButton("    -    ");
    JLabel str = new JLabel(strength);
    JLabel strV = new JLabel( strVal);
    JLabel strB = new JLabel( strBon);
    JLabel staV = new JLabel( staVal);
    JLabel staB = new JLabel( staBon);
    JLabel dexV = new JLabel( dexVal);
    JLabel dexB = new JLabel( dexBon);
    JLabel quiV = new JLabel( quiVal);
    JLabel quiB = new JLabel( quiBon);
    JLabel iqV = new JLabel( iqVal);
    JLabel iqB = new JLabel( iqBon);
    JLabel sprV = new JLabel( sprVal);
    JLabel sprB = new JLabel( sprBon);
    JLabel sta = new JLabel(stamina);
    JLabel dex = new JLabel(dexterity);
    JLabel qui = new JLabel(quickness);
    JLabel iq = new JLabel(intelligence);
    JLabel spr = new JLabel(spirit);
    JLabel hp = new JLabel(life);
    JLabel pow = new JLabel(power);
    JLabel styleRaceClass = new JLabel("Character");

    CreateNewGameGUI(){
        newGame.setLayout(new FlowLayout());
        newGame.setPreferredSize(new Dimension(780,580));
        newGame.setBackground(Color.BLACK);
        backToMain.setBounds(200,100,100,20);
        start.setBounds(200,300,100,20);
        selectStyle.setPreferredSize(new Dimension(250,170));
        selectStyle.add(divine);
        selectStyle.add(insane);
        selectStyle.add(diabolic);
        selectStyle.add(elusive);
        selectStyle.add(wise);
        selectRace.setPreferredSize(new Dimension(250,170));
        selectRace.add(human);
        selectRace.add(kobold);
        selectRace.add(dwarf);
        selectRace.add(undead);
        selectRace.add(elven);
        selectRace.add(troll);
        selectRace.add(ogre);
        selectRace.add(draconic);
        selectClass.setPreferredSize(new Dimension(250,170));
        selectClass.add(warrior);
        selectClass.add(priest);
        selectClass.add(rogue);
        selectClass.add(necro);
        selectClass.add(mage);
        bonusSection.setPreferredSize(new Dimension(400,350));
        bonusSection.setLayout(new FlowLayout());
        styleRaceClass.setPreferredSize(new Dimension(400, 20));
        bonusSection.add(styleRaceClass);
        str.setPreferredSize(new Dimension(100, 20));
        strV.setPreferredSize(new Dimension(50,20));
        strB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(str);
        bonusSection.add(strV);
        bonusSection.add(strB);
        bonusSection.add(strN);
        bonusSection.add(strP);
        sta.setPreferredSize(new Dimension(100, 20));
        staV.setPreferredSize(new Dimension(50,20));
        staB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(sta);
        bonusSection.add(staV);
        bonusSection.add(staB);
        bonusSection.add(staN);
        bonusSection.add(staP);
        dex.setPreferredSize(new Dimension(100, 20));
        dexV.setPreferredSize(new Dimension(50,20));
        dexB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(dex);
        bonusSection.add(dexV);
        bonusSection.add(dexB);
        bonusSection.add(dexN);
        bonusSection.add(dexP);
        qui.setPreferredSize(new Dimension(100, 20));
        quiV.setPreferredSize(new Dimension(50,20));
        quiB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(qui);
        bonusSection.add(quiV);
        bonusSection.add(quiB);
        bonusSection.add(quiN);
        bonusSection.add(quiP);
        iq.setPreferredSize(new Dimension(100, 20));
        iqV.setPreferredSize(new Dimension(50,20));
        iqB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(iq);
        bonusSection.add(iqV);
        bonusSection.add(iqB);
        bonusSection.add(iqN);
        bonusSection.add(iqP);
        spr.setPreferredSize(new Dimension(100, 20));
        sprV.setPreferredSize(new Dimension(50,20));
        sprB.setPreferredSize(new Dimension(50,20));
        bonusSection.add(spr);
        bonusSection.add(sprV);
        bonusSection.add(sprB);
        bonusSection.add(sprN);
        bonusSection.add(sprP);
        hp.setPreferredSize(new Dimension(175,20));
        bonusSection.add(hp);
        pow.setPreferredSize(new Dimension(175,20));
        bonusSection.add(pow);
        skillsSection.setPreferredSize(new Dimension(350,350));
        skillsSection.setLayout(new FlowLayout());
        melee.setVisible(false);
        magic.setVisible(false);
        spark.setVisible(false);
        smite.setVisible(false);
        sweep.setVisible(false);
        lifetap.setVisible(false);
        skillsSection.add(melee);
        skillsSection.add(magic);
        skillsSection.add(spark);
        skillsSection.add(smite);
        skillsSection.add(sweep);
        skillsSection.add(lifetap);   
        newGame.add(selectStyle);
        newGame.add(selectRace);
        newGame.add(selectClass);
        newGame.add(bonusSection);
        newGame.add(skillsSection);
        newGame.add(backToMain);
        newGame.add(start);
        newGame.setVisible(false);
    }
}//128